# Generated by Django 2.2.24 on 2021-08-20 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trunks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trunks',
            new_name='Trunk',
        ),
    ]
